#!/bin/bash

export LANGUAGE_SERVICE_KEY='YOUR_CONTENT_SAFETY_KEY'
export LANGUAGE_SERVICE_ENDPOINT='YOUR_CONTENT_SAFETY_ENDPOINT'

echo KEY = $LANGUAGE_SERVICE_KEY
echo ENDPOINT = $LANGUAGE_SERVICE_ENDPOINT