#!/bin/bash

export LANGUAGE_SERVICE_KEY='YOUR_LANGUAGE_SERVICE_KEY'
export LANGUAGE_SERVICE_ENDPOINT='YOUR_LANGUAGE_SERVICE_ENDPOINT'

echo KEY = $LANGUAGE_SERVICE_KEY
echo ENDPOINT = $LANGUAGE_SERVICE_ENDPOINT 