#!/bin/bash

export LANGUAGE_SERVICE_KEY='YOUR_CONTENT_SAFETY_KEY'
export LANGUAGE_SERVICE_ENDPOINT='YOUR_CONTENT_SAFETY_ENDPOINT'

echo KEY = $CONTENT_SAFETY_KEY
echo ENDPOINT = $CONTENT_SAFETY_ENDPOINT